# -*- coding: utf-8 -*-
"""Search+for+Green+Algae+28S+rRNA+sequences+and+Save+to+a+FASTA+file+(solution)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10wD0xkZ6OZu-dhW6Fc74U8vLvPGkPwZw
"""

'''
Copyright <2022> <Gail Rosen>

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
'''

'''
How many results do you get when you search for full 28 rRNA genes that are over 700 bp from a a) nematode, b) a green algae species, and c) an ascomycete fungus?  (Give a different number for a, b, and c).  
Please use Python to answer this – Hint:  print(records[‘Count’])
'''
# Install Biopython
# We are installing biopython version 1.68 because the latest version has removed Bio.Alphabet
!pip install biopython==1.68
from Bio import Entrez
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Alphabet import generic_dna, generic_protein

Entrez.email = 'ugwupaschal@gmail.com'

# [SLEN] means Sequence Length (in this case between 700 to 2000)
handle = Entrez.esearch(db="nucleotide", term="28S rRNA[gene] AND nematoda[ORGN] AND 700:2000[SLEN]")
records = Entrez.read(handle)
handle.close()
print("Found ",records['Count']," records");

handle = Entrez.esearch(db="nucleotide", term="28S rRNA[gene] AND green algae[ORGN] AND 700:2000[SLEN]")
green_algae_records = Entrez.read(handle)
handle.close()
print("Found ",green_algae_records['Count']," records");

handle = Entrez.esearch(db="nucleotide", term="28S rRNA[gene] AND ascomycota[ORGN] AND 700:2000[SLEN]")
records = Entrez.read(handle)
handle.close()
print("Found ",records['Count']," records");

'''
Save all 28 rRNA genes that are over 700 bp from all green algae species to a file named “long_28rrna_greenalgae.fa”
'''

#print(len(green_algae_records['IdList']))
handle = Entrez.esearch(db="nucleotide", term="28S rRNA[gene] AND green algae[ORGN] AND 700:2000[SLEN]",retmax=green_algae_records['Count'])
green_algae_records = Entrez.read(handle)
handle.close()
ID_list = ','.join(green_algae_records['IdList'])
handle = Entrez.efetch(db="nucleotide", id=ID_list, rettype="gb", retmode="xml")
genbank_records = Entrez.read(handle)

fasta_records = []
for i in range(len(genbank_records)):
	fasta_records.append(SeqRecord(Seq(genbank_records[i]['GBSeq_sequence']),id=genbank_records[i]['GBSeq_primary-accession'],description=genbank_records[i]['GBSeq_definition']))

long_file = open("long_28rrna_greenalgae.fasta","w")
SeqIO.write(fasta_records, long_file, "fasta")
long_file.close()